import { CompleteHero } from "@/lib/types";

export default {
  heroes: [
    {
      id: 3,
      name: "Countess",
      gender: "FEMALE",
      rangeType: "MELEE",
      heroPosition: [
        { id: 2, heroId: 3, position: "MID" },
        { id: 3, heroId: 3, position: "JUNGLE" },
        { id: 4, heroId: 3, position: "OFFLANE" },
      ],
      powerType: [{ id: 2, heroId: 3, powerType: "MAGICAL" }],
    },
    {
      id: 4,
      name: "Crunch",
      gender: "OTHER",
      rangeType: "MELEE",
      heroPosition: [{ id: 5, heroId: 4, position: "OFFLANE" }],
      powerType: [
        { id: 3, heroId: 4, powerType: "PHYSICAL" },
        { id: 4, heroId: 4, powerType: "MAGICAL" },
      ],
    },
    {
      id: 5,
      name: "Dekker",
      gender: "FEMALE",
      rangeType: "RANGED",
      heroPosition: [{ id: 6, heroId: 5, position: "SUPPORT" }],
      powerType: [{ id: 5, heroId: 5, powerType: "MAGICAL" }],
    },
    {
      id: 6,
      name: "Drongo",
      gender: "MALE",
      rangeType: "RANGED",
      heroPosition: [{ id: 7, heroId: 6, position: "CARRY" }],
      powerType: [{ id: 6, heroId: 6, powerType: "PHYSICAL" }],
    },
    {
      id: 7,
      name: "Feng Mao",
      gender: "MALE",
      rangeType: "MELEE",
      heroPosition: [
        { id: 8, heroId: 7, position: "OFFLANE" },
        { id: 9, heroId: 7, position: "JUNGLE" },
      ],
      powerType: [{ id: 7, heroId: 7, powerType: "PHYSICAL" }],
    },
    {
      id: 8,
      name: "Gadget",
      gender: "FEMALE",
      rangeType: "RANGED",
      heroPosition: [{ id: 10, heroId: 8, position: "MID" }],
      powerType: [{ id: 8, heroId: 8, powerType: "MAGICAL" }],
    },
    {
      id: 9,
      name: "Gideon",
      gender: "MALE",
      rangeType: "RANGED",
      heroPosition: [{ id: 11, heroId: 9, position: "MID" }],
      powerType: [{ id: 9, heroId: 9, powerType: "MAGICAL" }],
    },
    {
      id: 10,
      name: "Grux",
      gender: "MALE",
      rangeType: "MELEE",
      heroPosition: [
        { id: 12, heroId: 10, position: "OFFLANE" },
        { id: 13, heroId: 10, position: "JUNGLE" },
      ],
      powerType: [{ id: 10, heroId: 10, powerType: "PHYSICAL" }],
    },
    {
      id: 11,
      name: "Howitzer",
      gender: "MALE",
      rangeType: "RANGED",
      heroPosition: [{ id: 14, heroId: 11, position: "MID" }],
      powerType: [{ id: 11, heroId: 11, powerType: "MAGICAL" }],
    },
    {
      id: 12,
      name: "Kallari",
      gender: "FEMALE",
      rangeType: "MELEE",
      heroPosition: [
        { id: 15, heroId: 12, position: "OFFLANE" },
        { id: 16, heroId: 12, position: "JUNGLE" },
      ],
      powerType: [{ id: 12, heroId: 12, powerType: "PHYSICAL" }],
    },
    {
      id: 13,
      name: "Khaimera",
      gender: "MALE",
      rangeType: "MELEE",
      heroPosition: [{ id: 17, heroId: 13, position: "JUNGLE" }],
      powerType: [{ id: 13, heroId: 13, powerType: "PHYSICAL" }],
    },
    {
      id: 14,
      name: "Muriel",
      gender: "FEMALE",
      rangeType: "RANGED",
      heroPosition: [{ id: 18, heroId: 14, position: "SUPPORT" }],
      powerType: [{ id: 14, heroId: 14, powerType: "MAGICAL" }],
    },
    {
      id: 15,
      name: "Murdock",
      gender: "MALE",
      rangeType: "RANGED",
      heroPosition: [{ id: 19, heroId: 15, position: "CARRY" }],
      powerType: [{ id: 15, heroId: 15, powerType: "PHYSICAL" }],
    },
    {
      id: 16,
      name: "Narbash",
      gender: "MALE",
      rangeType: "MELEE",
      heroPosition: [{ id: 20, heroId: 16, position: "SUPPORT" }],
      powerType: [{ id: 16, heroId: 16, powerType: "MAGICAL" }],
    },
    {
      id: 17,
      name: "Riktor",
      gender: "MALE",
      rangeType: "MELEE",
      heroPosition: [
        { id: 21, heroId: 17, position: "OFFLANE" },
        { id: 22, heroId: 17, position: "JUNGLE" },
        { id: 23, heroId: 17, position: "SUPPORT" },
      ],
      powerType: [{ id: 17, heroId: 17, powerType: "MAGICAL" }],
    },
    {
      id: 18,
      name: "Sevarog",
      gender: "MALE",
      rangeType: "MELEE",
      heroPosition: [
        { id: 24, heroId: 18, position: "OFFLANE" },
        { id: 25, heroId: 18, position: "JUNGLE" },
      ],
      powerType: [{ id: 18, heroId: 18, powerType: "MAGICAL" }],
    },
    {
      id: 19,
      name: "Steel",
      gender: "MALE",
      rangeType: "MELEE",
      heroPosition: [
        { id: 26, heroId: 19, position: "OFFLANE" },
        { id: 27, heroId: 19, position: "JUNGLE" },
        { id: 28, heroId: 19, position: "SUPPORT" },
      ],
      powerType: [{ id: 19, heroId: 19, powerType: "MAGICAL" }],
    },
    {
      id: 20,
      name: "Shinbi",
      gender: "FEMALE",
      rangeType: "MELEE",
      heroPosition: [
        { id: 29, heroId: 20, position: "OFFLANE" },
        { id: 30, heroId: 20, position: "JUNGLE" },
        { id: 31, heroId: 20, position: "JUNGLE" },
      ],
      powerType: [{ id: 20, heroId: 20, powerType: "MAGICAL" }],
    },
    {
      id: 21,
      name: "Sparrow",
      gender: "FEMALE",
      rangeType: "RANGED",
      heroPosition: [{ id: 32, heroId: 21, position: "CARRY" }],
      powerType: [{ id: 21, heroId: 21, powerType: "PHYSICAL" }],
    },
    {
      id: 22,
      name: "The Fey",
      gender: "FEMALE",
      rangeType: "RANGED",
      heroPosition: [{ id: 33, heroId: 22, position: "MID" }],
      powerType: [{ id: 22, heroId: 22, powerType: "MAGICAL" }],
    },
    {
      id: 23,
      name: "Revenant",
      gender: "MALE",
      rangeType: "RANGED",
      heroPosition: [{ id: 34, heroId: 23, position: "CARRY" }],
      powerType: [{ id: 23, heroId: 23, powerType: "PHYSICAL" }],
    },
    {
      id: 24,
      name: "Rampage",
      gender: "MALE",
      rangeType: "MELEE",
      heroPosition: [{ id: 35, heroId: 24, position: "JUNGLE" }],
      powerType: [{ id: 24, heroId: 24, powerType: "PHYSICAL" }],
    },
    {
      id: 25,
      name: "Kira",
      gender: "FEMALE",
      rangeType: "RANGED",
      heroPosition: [{ id: 36, heroId: 25, position: "CARRY" }],
      powerType: [{ id: 25, heroId: 25, powerType: "PHYSICAL" }],
    },
    {
      id: 26,
      name: "Lt. Belica",
      gender: "FEMALE",
      rangeType: "RANGED",
      heroPosition: [
        { id: 37, heroId: 26, position: "MID" },
        { id: 38, heroId: 26, position: "SUPPORT" },
      ],
      powerType: [{ id: 26, heroId: 26, powerType: "MAGICAL" }],
    },
  ] as CompleteHero[],
  todaysHero: {
    id: 8,
    name: "Gadget",
    gender: "FEMALE",
    rangeType: "RANGED",
    heroPosition: [{ id: 10, heroId: 8, position: "MID" }],
    powerType: [{ id: 8, heroId: 8, powerType: "MAGICAL" }],
  } as CompleteHero,
};
