name: daily-cron-job
on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:
    inputs:
      hello:
        type: string
jobs:
  cron:
    runs-on: ubuntu-latest
    env:
      CRON_PASS: ${{ secrets.CRON_PASS }}
    steps:
      - name: daily-cron-job
        run: |
          curl --request POST \
          --url 'https://predle.vercel.app/api/admin/hero/answer' \
          --header "Authorization: $CRON_PASS"
